######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 12 16:22:32 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += qt.cc
